---
- name: Configure host.
  hosts: all

  tasks:
  - name: Install a list of ports
    community.general.macports:
      name: "{{ ports }}"
    become: true
    vars:
      ports:
        - coreutils
        - eza
        - zoxide
        - starship
        - wget
        - qemu
        - htopß